{"name": "Cannot update the integer param of \"number_of_done_iterations_to_show\" of project with extreme values -- @1.4 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562461152, "stop": 1556562461153}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "307e8226-28e5-4a88-bb7b-d02d158aa5bb-attachment.txt", "type": "text/plain"}], "start": 1556562461153, "stop": 1556562461154}, {"name": "When I send the request", "status": "passed", "start": 1556562461155, "stop": 1556562461617}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562461617, "stop": 1556562461619}, {"name": "And I verify the general_problem of error is: \"'number_of_done_iterations_to_show' must be an integer value\"", "status": "passed", "start": 1556562461619, "stop": 1556562461632}], "parameters": [{"name": "number", "value": "true"}, {"name": "message", "value": "'number_of_done_iterations_to_show' must be an integer value"}], "start": 1556562461151, "stop": 1556562461632, "uuid": "3fe52d95-9edb-4d15-89d0-8fad88cef493", "historyId": "0d50623e6ee7fd19ede1240dc9480920", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}